### PR TITLE
Fix npm start for server

### PR DESCRIPTION
**Pull request by jemiluv8**
Modify workspace configuration to make the above command work.

```sh
npm run start -w=@tern-app/server
```

### Background
The above command was failing because our server "code" used commonjs instead of module.
So we needed to 'build' to target commonjs. That fixed the start command for the server but broke the 
build command for the client application.

### Hybrid builds for cjs and mjs
I ended up building our shared package for both esm and commonjs targets.
And used the conditional exports to match the appropriate entry point for the calling code.

fixes /#1
/claim #1

### CODE REVIEW

**Comment by leggetter** [comment]
Hey @jemiluv8 - great progress on the build 👍 

Unforutnately, it looks like this breaks the dev flow:

If I install dependencies, setup the Tigris project, and run `npm run dev -w=@tern-app/client` I get the following error:

```
[vite] Internal server error: Failed to resolve entry for package "@tern-app/shared". The package may have incorrect main/module/exports specified in its package.json.
  Plugin: vite:import-analysis
  File: /Users/leggetter/tmp/tern-stack-template/apps/client/src/App.tsx
      at packageEntryFailure (file:///Users/leggetter/tmp/tern-stack-template/node_modules/vite/dist/node/chunks/dep-a178814b.js:23384:11)
      at resolvePackageEntry (file:///Users/leggetter/tmp/tern-stack-template/node_modules/vite/dist/node/chunks/dep-a178814b.js:23381:5)
      at tryNodeResolve (file:///Users/leggetter/tmp/tern-stack-template/node_modules/vite/dist/node/chunks/dep-a178814b.js:23115:20)
      at Context.resolveId (file:///Users/leggetter/tmp/tern-stack-template/node_modules/vite/dist/node/chunks/dep-a178814b.js:22876:28)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async Object.resolveId (file:///Users/leggetter/tmp/tern-stack-template/node_modules/vite/dist/node/chunks/dep-a178814b.js:42805:32)
      at async TransformContext.resolve (file:///Users/leggetter/tmp/tern-stack-template/node_modules/vite/dist/node/chunks/dep-a178814b.js:42533:23)
      at async normalizeUrl (file:///Users/leggetter/tmp/tern-stack-template/node_modules/vite/dist/node/chunks/dep-a178814b.js:40501:34)
      at async file:///Users/leggetter/tmp/tern-stack-template/node_modules/vite/dist/node/chunks/dep-a178814b.js:40652:47
      at async Promise.all (index 10)
      at async TransformContext.transform (file:///Users/leggetter/tmp/tern-stack-template/node_modules/vite/dist/node/chunks/dep-a178814b.js:40578:13)
      at async Object.transform (file:///Users/leggetter/tmp/tern-stack-template/node_modules/vite/dist/node/chunks/dep-a178814b.js:42877:30)
      at async loadAndTransform (file:///Users/leggetter/tmp/tern-stack-template/node_modules/vite/dist/node/chunks/dep-a178814b.js:53334:29)
```

I'd like the shared contents to run from source in development mode.

**Comment by jemiluv8** [comment]
@leggetter I was able to accidentally replicate the same error locally (once) but have since not been able to do so.
Can you try the following

- Use node v18.16+
- delete all node modules folder under apps/client and in the root folder
- run the dev command for client again.

In the meantime I'm still looking to replicate the error again and understand the "cause" better.

PS: Can you share your node version?

**Comment by leggetter** [comment]
@jemiluv8 I'm on node v19.8.1

I pulled the repo down from scratch earlier in a new tmp directory and followed the process I've documented and just recorded [and published a video](https://www.youtube.com/watch?v=-ZoxNLbln7o&ab_channel=Tigris) of following, so that flow really needs to keep working 🤞 

VScode reports an error with the shared import within the client:

CleanShot 2023-05-10 at 17 13 15

I haven't built the shared package and it would be better if the solution wasn't to continuously build that and use everything from source in dev mode.

**Comment by jemiluv8** [comment]
@leggetter I've come up with solution #2 hope you check it out and give feedback.
It works with the existing flows and fixes the npm run start for the app server

**Background (2)** 
Again it was just a matter of building a common js version of the shared package to be used when 
running the server build using the "node" directly.

Key modifications

- use typescript project references and tsc --build (build mode) to ensure that whenever a ts module is build, its "referenced" packages are also built. 
- Add relevant conditional exports to the shared package to ensure that the commonjs build is referenced in the "production" "condition" for node.

**Pull request closed without merging**
